# Generated by Django 3.2.16 on 2024-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Поле необязательно для заполения', max_length=20, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='День рождения')),
            ],
        ),
    ]
